#nom des fichiers en sortie sans extension
NAMES      = sea
CPU        = -mmcu=msp430x1611

#chemin vers le dossier contenant tools.h et le mspgcc.makefile
UTILS_PATH = ../utils

#nom des fichiers sources (dépendances générées automatiquement)
SRC              = sea.c
INCLUDES         = -I${UTILS_PATH} 

-include ${UTILS_PATH}/mspgcc.makefile

