UTILS_PATH = ../utils

# define one name for each executable to be built
NAMES      = xtea

# sources files specific to 'first_target'
SRC              = xtea.c
INCLUDES         = -I${UTILS_PATH} 

-include ${UTILS_PATH}/mspgcc.makefile
