# define one name for each executable to be built
NAMES      = simon96_144
CPU        = -mmcu=msp430f1611
UTILS_PATH = ../utils

# sources files specific to 'first_target'
SRC              = simon96_144.c
INCLUDES         = -I${UTILS_PATH} -Icommon

-include ${UTILS_PATH}/mspgcc.makefile

