# define one name for each executable to be built
NAMES      = present
CPU        = -mmcu=msp430x1611
UTILS_PATH = ../utils

# sources files specific to 'first_target'
SRC              = present_speed.c
INCLUDES         = -I${UTILS_PATH}

-include ${UTILS_PATH}/mspgcc.makefile

