# define one name for each executable to be built
NAMES      = led

UTILS_PATH = ../utils

# sources files specific to 'first_target'
SRC              = LED64_tdur.c
INCLUDES         = -I${UTILS_PATH}

-include ${UTILS_PATH}/mspgcc.makefile
